Remove $ symbol from readme to allow strigthforward copy-paste function
pyenv/pyenv-installer pull request #111
Opened 2021-05-17 23:00 UTC by rola93

Git now offers a copy button on code snippets (check it on the right-up corner), as you can see in the following image:

![screenshoot shows the copy icon on code snippet](https://i.imgur.com/VmVI8GZ.png)

The icon is very useful and let you copy the code snippet. The problem is that current version of Readme includes the `$` char which makes it hard: you copy with just one click, but when you paste it, need to delete it before running the command. 

It's far easier to just remove the char and then the button copies the ready-to-run code

2021-05-25 05:20 UTC, native-api commented
The "`$`" is a conventional indicator that is a command invocation that should be run directly in a UNIX shell prompt (as e.g. opposed to inserted into some configuration file). Without it, that'd be unclear.

This indicator has been used in the UNIX community for decades. If Github ignores this convention in its feature, it's a problem with Github.

Should be ditch the indicator to indulge Github in their ignorant behavior, we need to invent some other indication that would tell the user the same. But due to how ubiquitous and succinct this convention is, I seriously doubt you could come up with anything that could compare.

2021-05-25 05:28 UTC, native-api requested changes
The "`$`" is a conventional indicator that this is a command invocation that should be run directly in a UNIX shell prompt (as e.g. opposed to inserted into some configuration file). Without it, that'd be unclear.

This indicator has been used in the UNIX community for decades. If Github ignores this convention in their feature, it's a problem with Github.

Should we ditch the indicator, we need to invent some other indication that would tell the user the same. But due to how ubiquitous and succinct this convention is, I seriously doubt you could come up with anything that could compare.

2021-05-27 22:07 UTC, rola93 commented
It'sa good point, but from a user perspective, I think it is clear enough with the context.

I see it far more useful to let the user copy-paste functionality as is, and take advantage of it.

In fact, [pyenv](https://github.com/pyenv/pyenv-virtualenv) itself do not use the `$` char in their docs.

2021-06-08 06:37 UTC, native-api commented
> In fact, [pyenv](https://github.com/pyenv/pyenv-virtualenv) itself do not use the `$` char in their docs.

Okay, that makes sense.

2021-06-08 06:37 UTC, merged