`-set u` to catch missing $HOME
pyenv/pyenv-installer pull request #146
Opened 2023-03-31 23:53 UTC by marcospgp

I'm installing pyenv in a cloud-init config file, which runs in a context that has no `$HOME` env variable.

It seems pyenv installation relies on this value, and if it is not set, fails silently (installs `.pyenv` directory into `/` the root directory).

2023-04-01 13:39 UTC, native-api requested changes
```
./pyenv-installer: line 4: PYENV_DEBUG: unbound variable
```

2023-04-01 17:07 UTC, marcospgp commented
@native-api Whoops, my bad for calling with `curl https://pyenv.run | (set -euxo pipefail && bash)`.

Updated PR, can you review?

2023-04-01 17:11 UTC, native-api reviewed
Shall we update `pyenv-offline-installer`, too?

2023-04-01 17:17 UTC, native-api commented
Maybe it's easier to just check for `HOME` specifically?

Since we don't require the same for any other variables.

2023-04-01 17:19 UTC, native-api commented
`${HOME:-?}`

2023-04-02 11:55 UTC, marcospgp commented
@native-api good point, only `$HOME` seems to cause a bug if unset. Updated PR

2023-04-02 13:33 UTC, native-api commented
Since we only (currently) need `HOME` if the install location is not specificed explicitly via `PYENV_ROOT`, I moved the test there.

Is that okay?

2023-06-09 20:27 UTC, derek-olds commented
This seems like it could default to /opt without causing problems. Is there a reason that it doesn't get pushed there on install? I know I was surprised to find it in home when I didn't set PYENV_ROOT.

2023-06-10 12:37 UTC, merged